name: Deployment Workflow
on:
  push:
    branches: [ master ]
  
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ssh pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.ssh_key }}
        port: 22
        script: |
          cd /home/${{ secrets.user }}/Discord-Bot
          git pull origin master
          git status